[workspace]
members = ["ssr"]
resolver = "2"

[workspace.package]
publish = false
edition = "2021"


# Defines a size-optimized profile for the WASM bundle in release mode
[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"