[env]
RUSTFLAGS = "--cfg=web_sys_unstable_apis"

[target.wasm32-unknown-unknown]
rustflags = ["--cfg", "getrandom_backend=\"wasm_js\""]

[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"  # Change to match your symlink
rustflags = ["-C", "target-feature=+crt-static"]