set +a 

source .env 

export RUST_LOG="estate_fe=debug,tower_http=debug"
export RUST_BACKTRACE=1
export LEPTOS_SITE_ROOT="target/site"
export PAYMENTS_SKIP_LOCAL="true"
export LEPTOS_SITE_ADDR="127.0.0.1:3002"
export NOWPAYMENTS_API_HOST="http://localhost:3001"

export LEPTOS_HASH_FILES="true"

cargo leptos build --release --lib-features "release-lib-prod" --bin-features "release-bin-prod" || exit 1
COOKIE_KEY=$COOKIE_KEY LITEAPI_KEY=$LITEAPI_KEY BASIC_AUTH_PASSWORD_FOR_LEPTOS_ROUTE=$BASIC_AUTH_PASSWORD_FOR_LEPTOS_ROUTE BASIC_AUTH_USERNAME_FOR_LEPTOS_ROUTE=$BASIC_AUTH_USERNAME_FOR_LEPTOS_ROUTE LITEAPI_PREBOOK_BASE_URL=$LITEAPI_PREBOOK_BASE_URL STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY EMAIL_CLIENT_ID=$EMAIL_CLIENT_ID EMAIL_CLIENT_SECRET=$EMAIL_CLIENT_SECRET EMAIL_REFRESH_TOKEN=$EMAIL_REFRESH_TOKEN EMAIL_TOKEN_EXPIRY=$EMAIL_TOKEN_EXPIRY EMAIL_ACCESS_TOKEN=$EMAIL_ACCESS_TOKEN ESTATE_DAO_SNS_PROPOSAL_SUBMISSION_IDENTITY_PRIVATE_KEY=$ESTATE_DAO_SNS_PROPOSAL_SUBMISSION_IDENTITY_PRIVATE_KEY PROVAB_HEADERS=$PROVAB_HEADERS NOW_PAYMENTS_USDC_ETHEREUM_API_KEY=$NOW_PAYMENTS_USDC_ETHEREUM_API_KEY ./target/release/estate-fe



 set -a