name: Deploy to Fly prod on tag push
on:  
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy from'
        required: true
        default: 'main'
        type: string


concurrency:
  group: production-deployment
  cancel-in-progress: true


jobs:
  build_check_prod:
    uses: ./.github/workflows/build-check-prod.yml
    with:
      publish-artifact: true

  deploy:
    name: Deploy
    needs: build_check_prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build-debian
      - name: Show directory structure
        run: tree -a || (apt-get update && apt-get install -y tree && tree -a)
      - name: Remove .dockerignore
        run: rm -f .dockerignore
      
      - run: chmod +x target/release/estate-fe
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Export secret with single quotes
        run: |
          flyctl secrets set  ESTATE_DAO_SNS_PROPOSAL_SUBMISSION_IDENTITY_PRIVATE_KEY="$ESTATE_DAO_SNS_PROPOSAL_SUBMISSION_IDENTITY_PRIVATE_KEY"  --app "nofeebooking" --stage
          flyctl secrets set  PROVAB_HEADERS="$PROVAB_HEADERS" FLY_API_TOKEN="$FLY_API_TOKEN" NOW_PAYMENTS_USDC_ETHEREUM_API_KEY="$NOW_PAYMENTS_USDC_ETHEREUM_API_KEY" ESTATE_DAO_SNS_PROPOSAL_SUBMISSION_IDENTITY_PRIVATE_KEY="$ESTATE_DAO_SNS_PROPOSAL_SUBMISSION_IDENTITY_PRIVATE_KEY" BASIC_AUTH_PASSWORD_FOR_LEPTOS_ROUTE="$BASIC_AUTH_PASSWORD_FOR_LEPTOS_ROUTE" BASIC_AUTH_USERNAME_FOR_LEPTOS_ROUTE="$BASIC_AUTH_USERNAME_FOR_LEPTOS_ROUTE" COOKIE_KEY="$COOKIE_KEY" EMAIL_ACCESS_TOKEN="$EMAIL_ACCESS_TOKEN" EMAIL_CLIENT_ID="$EMAIL_CLIENT_ID" EMAIL_CLIENT_SECRET="$EMAIL_CLIENT_SECRET" EMAIL_REFRESH_TOKEN="$EMAIL_REFRESH_TOKEN" EMAIL_TOKEN_EXPIRY="$EMAIL_TOKEN_EXPIRY" LITEAPI_KEY="$LITEAPI_KEY" LITEAPI_PREBOOK_BASE_URL="$LITEAPI_PREBOOK_BASE_URL" NOWPAYMENTS_IPN_SECRET="$NOWPAYMENTS_IPN_SECRET" STRIPE_SECRET_KEY="$STRIPE_SECRET_KEY" YRAL_AUTH_CLIENT_ID="$YRAL_AUTH_CLIENT_ID" YRAL_AUTH_CLIENT_SECRET="$YRAL_AUTH_CLIENT_SECRET" YRAL_AUTH_REDIRECT_URL="$YRAL_AUTH_REDIRECT_URL" --app "nofeebooking" --stage
        env:
          PROVAB_HEADERS: ${{ secrets.PROVAB_PRODUCTION_ENVIRONMENT_REQUEST_HEADER_CONTENTS }}
          FLY_API_TOKEN: ${{ secrets.FLY_IO_PRODUCTION_ENVIRONMENT_DEPLOY_TOKEN }}
          NOW_PAYMENTS_USDC_ETHEREUM_API_KEY: ${{secrets.NOW_PAYMENTS_USDC_ETHEREUM_API_KEY}}
          ESTATE_DAO_SNS_PROPOSAL_SUBMISSION_IDENTITY_PRIVATE_KEY: ${{secrets.ESTATE_DAO_SNS_PROPOSAL_SUBMISSION_IDENTITY_PRIVATE_KEY}}
          BASIC_AUTH_PASSWORD_FOR_LEPTOS_ROUTE: ${{secrets.BASIC_AUTH_PASSWORD_FOR_LEPTOS_ROUTE}}
          BASIC_AUTH_USERNAME_FOR_LEPTOS_ROUTE: ${{secrets.BASIC_AUTH_USERNAME_FOR_LEPTOS_ROUTE}}
          COOKIE_KEY: ${{secrets.COOKIE_KEY}}
          EMAIL_ACCESS_TOKEN: ${{secrets.EMAIL_ACCESS_TOKEN}}
          EMAIL_CLIENT_ID: ${{secrets.EMAIL_CLIENT_ID}}
          EMAIL_CLIENT_SECRET: ${{secrets.EMAIL_CLIENT_SECRET}}
          EMAIL_REFRESH_TOKEN: ${{secrets.EMAIL_REFRESH_TOKEN}}
          EMAIL_TOKEN_EXPIRY: ${{secrets.EMAIL_TOKEN_EXPIRY}}
          LITEAPI_KEY: ${{secrets.LITEAPI_KEY}}
          LITEAPI_PREBOOK_BASE_URL: ${{secrets.LITEAPI_PREBOOK_BASE_URL}}
          NOWPAYMENTS_IPN_SECRET: ${{secrets.NOWPAYMENTS_IPN_SECRET}}
          STRIPE_SECRET_KEY: ${{secrets.STRIPE_SECRET_KEY}}
          YRAL_AUTH_CLIENT_ID: ${{secrets.YRAL_AUTH_CLIENT_ID}}
          YRAL_AUTH_CLIENT_SECRET: ${{secrets.YRAL_AUTH_CLIENT_SECRET}}
          YRAL_AUTH_REDIRECT_URL: ${{secrets.YRAL_AUTH_REDIRECT_URL}}
          
      
      - name: Deploy a docker container to Fly.io
        run: flyctl deploy --remote-only -c fly-prod.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_PRODUCTION_ENVIRONMENT_DEPLOY_TOKEN }}